//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAsaveMyphoto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaveMyPhotoEntities : DbContext
    {
        public SaveMyPhotoEntities()
            : base("name=SaveMyPhotoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dispositivi> Dispositivi { get; set; }
        public virtual DbSet<Media> Media { get; set; }
        public virtual DbSet<Utenti> Utenti { get; set; }
        public virtual DbSet<Foto> Foto { get; set; }
        public virtual DbSet<Video> Video { get; set; }
    }
}
